spring:
  profiles:
    active: dev
s3:
  upload:
    duration:
      seconds: 86400
    limitBytes: 10000000000
    acl: private
  download:
    duration:
      seconds: 600
sts:
  min:
    duration:
      minutes: 15